### PR TITLE
Rails assets fixes

### PR DESCRIPTION
**Pull request by harrisj**
So, I have been doing a bit of testing with the Micropurchase app's Rail asset pipeline and the Web Standards gem. I think I have fixed the issues with Rails and images (or at least it looks like I have when I run it locally and deploy to staging). The main difference was replacing the `url()` directives in SCSS with `image-url()` and `font-url()` used by Rails' SCSS. I also added a method for explicitly returning the images directory in case it needs to be added to the assets path, but it doesn't seem to be needed actually. Nor is it necessary to precompile the images (both tips taken from the [Gemoji project](https://github.com/github/gemoji).

This seems to work with Jekyll and SCSS, but I really am not sure it's totally cool and I'd like to see how it looks for a Jekyll template that has images and fonts on its pages. I don't really have the expertise in Jekyll, but if one of you could investigate for me, I'd be very grateful. **DO NOT MERGE** until you can confirm it doesn't break Jekyll.

Note: if you have copied over images/fonts to your application directory, this sometimes create problems when you deploy, where the CSS is rewritten to point to the wrong location. I still need to figure that one out.

### CODE REVIEW

**Comment by pkarman** [comment]
@harrisj this is to supercede #6 ?

It would be nice if we had some tests to verify. We are starting to use this gem with e-manifest. Maybe @jeremiak could test in his dev env?

**Comment by jessieay** [comment]
@harrisj these changes looks great and are in line with changes I've made in the past to deal with asset pipeline issues. not sure if this is mentioned elsewhere, but rails project do need to 12 factor gem in order for these asset references to work properly on cloud foundry. see https://github.com/thoughtbot/bourbon/pull/250#issuecomment-25108881

+1 to what Pkarman said about having someone try this out on a e-manifest.

**Comment by harrisj** [comment]
This was done separately from #6 (bad Jake!) but I don't think the SCSS `url()` declarations are rewritten to the digest versions by Rails unlike `image-url`... but I am not sure if that creates any issues of its own.

I would love test suggestions. Right now I've just been eyeballing and deploying and asset pre compiling and looking for 404s so anything more rigorous is good.

**Comment by pkarman** [comment]
I can confirm this fixes 404 image assets on a Rails app (e-manifest).

I don't have an existing Jekyll app to test with. Do we know of any Jekyll apps currently using this gem? https://github.com/18F/federalist does not seem to be.

**Comment by harrisj** [comment]
Do we have anybody who knows Jekyll who can confirm if this is okay?

**Comment by pkarman** [comment]
At this point, I suggest that we identify any existing Jekyll apps that rely on this gem and check them for regressions.

**Comment by jessieay** [comment]
I am working on e-manifest and just tried to use this branch. fixed asset loading issue but presented a new one:

```
1) Create manifest fills in all fields
     Failure/Error: Unable to find matching line from backtrace
     ActionView::Template::Error:
       undefined method `[]' for nil:NilClass
     # ./app/views/layouts/application.html.erb:13:in `_app_views_layouts_application_html_erb__734565610918292024_701310269517
```

L13 is where I am including my application javascript file. this error does not arise in development, only in tests. Also confirmed that it is not an issue with the rubygems version of uswds gem.

**Comment by jessieay** [comment]
Just figured out the issue - one of the files in this gem was appended with `css` instead of `scss` 

What I was seeing was described here: http://stackoverflow.com/a/13185741

I forked your fork, Jacob, and the change here fixed my problem https://github.com/jessieay/us_web_design_standards_gem/commit/0d777d5ee7c486e64733944cce5ab4d35c6f6c95

Since I can't contribute back directly to this PR, perhaps you can make the change on your fork?

**Comment by jessieay** [comment]
If you'd like to replicate this issue see: https://github.com/18F/e-manifest/pull/130/files

If you revert back to Jacob's version of this branch and try to run the tests, you will see the `undefined method '[]' for nil:NilClass` error when running `bundle exec rspec spec/features/create_manifest_spec.rb:34` -- with my small change on top of his, the spec passes

**Comment by rogeruiz** [comment]
There is a big ol' refactor coming here 18F/web-design-standards#978. I'd like to help out in getting this fixed within my own PR ( 18F/web-design-standards#980 ) as well, which will possibly add automation to releasing this ruby gem and keep it more in sync with the standards. Let me know how I can help.

**Comment by jessieay** [comment]
ping ping @harrisj -- thoughts on my last comment?

**Comment by harrisj** [comment]
Hmm, not sure why I wasn't getting these Github notifications (argh), but I am reading it now. @jessieay I would like you to get the git credit for fixing that, so I have added you as a collaborator to my fork if that's okay. Or I can apply the changes now.

@rogeruiz, should we be bothering with all this in light of your upcoming reorganization?

**Comment by harrisj** [comment]
Never mind, I made the change. Many apologies again for missing this thread being updated. Will go check my mail and notification settings.

**Comment by jessieay** [comment]
@harrisj :+1: yay! no worries about not seeing the comment.

**Comment by rogeruiz** [comment]
I think it's okay to include your changes in this PR @harrisj. My refactor update will only be updating the contents of the directories you are editing. It seems like the workflow in 18f/web-design-standards#980 is going to have to be updated to support generating the correct `image-url` and `asset-url` property values. for Rails.

**Comment by rogeruiz** [comment]
@harrisj This does break images, and I'm assuming other assets, on Jekyll sites because of the files in `assets` being modified to use the `image-url` and `asset-url` Rails helpers.

After reverting the changes only in the `assets` directory, this should be okay to merge. :+1:

**Comment by harrisj** [comment]
So, to clarify, I should have just made changes to files in `/app/assets/*` and not `/assets/*`?

**Comment by rogeruiz** [comment]
Yup

**Comment by harrisj** [comment]
Okay, done. Thanks!

**Comment by rogeruiz** [comment]
Great @harrisj! The latest changes fix the asset issues in the Jekyll. This _would_ be good to merge into `master`, but I'm hesitant too without more information on whether this `gem` is considered a Jekyll plugin or a Rails `gem` and Jekyll plugin. I'm posting more information in the issue associated with the refactor => #15.

**Comment by jessieay** [comment]
I just worked off of this PR to get the latest version of USWDS (0.9.4) to work with Rails. PR here: https://github.com/18F/micropurchase/pull/737

**Comment by pkarman** [comment]
@jessieay were you using your fork? or this branch?

**Comment by jessieay** [comment]
Miropurchase isn't using the gem for CSS, web design standards assets were copied into the `vendor` directory of the Rails app. 

So when I went to update I deleted the USWDS from `vendor`, installed the newest version of USWDS via NPM, copied them into `vendor`, and then updated the copied code to comply with rails asset pipeline. I used this PR to point me to which files needed to be updated (although the design standards have changed quiet a bit since this PR)

Would like to find a better way to do this since updating vendored code is not ideal. Will be excited to use Gem when it is ready! cc @rogeruiz

**Comment by pkarman** [comment]
Can we close this? See https://github.com/18F/us_web_design_standards_gem/issues/15#issuecomment-237958605

**Pull request closed without merging**
